import {
  BlackBishop,
  BlackKnight,
  BlackPawn,
  BlackQueen,
  BlackRook,
  BlackKing,
  WhiteBishop,
  WhiteKnight,
  WhiteKing,
  WhitePawn,
  WhiteQueen,
  WhiteRook,
} from "../components/PieceSVG";
import { SquareOccupancy } from "./interfaces";

const initialPiecePositions: SquareOccupancy[] = [
  {
    id: "black-rook-0",
    pieceType: "rook",
    pieceColor: "black",
    pieceSVG: BlackRook(),
    x: 0,
    y: 0,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-knight-1",
    pieceType: "knight",
    pieceColor: "black",
    pieceSVG: BlackKnight(),
    x: 0,
    y: 1,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-bishop-2",
    pieceType: "bishop",
    pieceColor: "black",
    pieceSVG: BlackBishop(),
    x: 0,
    y: 2,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-queen",
    pieceType: "queen",
    pieceColor: "black",
    pieceSVG: BlackQueen(),
    x: 0,
    y: 3,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-king",
    pieceType: "king",
    pieceColor: "black",
    pieceSVG: BlackKing(),
    x: 0,
    y: 4,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-bishop-5",
    pieceType: "bishop",
    pieceColor: "black",
    pieceSVG: BlackBishop(),
    x: 0,
    y: 5,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-knight-6",
    pieceType: "knight",
    pieceColor: "black",
    pieceSVG: BlackKnight(),
    x: 0,
    y: 6,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-rook-7",
    pieceType: "rook",
    pieceColor: "black",
    pieceSVG: BlackRook(),
    x: 0,
    y: 7,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-0",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 0,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-1",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 1,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-2",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 2,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-3",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 3,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-4",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 4,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-5",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 5,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-6",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 6,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "black-pawn-7",
    pieceType: "pawn",
    pieceColor: "black",
    pieceSVG: BlackPawn(),
    x: 1,
    y: 7,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-0",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 0,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-1",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 1,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-2",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 2,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-3",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 3,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-4",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 4,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-5",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 5,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-6",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 6,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-pawn-7",
    pieceType: "pawn",
    pieceColor: "white",
    pieceSVG: WhitePawn(),
    x: 6,
    y: 7,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-rook-0",
    pieceType: "rook",
    pieceColor: "white",
    pieceSVG: WhiteRook(),
    x: 7,
    y: 0,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-knight-1",
    pieceType: "knight",
    pieceColor: "white",
    pieceSVG: WhiteKnight(),
    x: 7,
    y: 1,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-bishop-2",
    pieceType: "bishop",
    pieceColor: "white",
    pieceSVG: WhiteBishop(),
    x: 7,
    y: 2,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-queen",
    pieceType: "queen",
    pieceColor: "white",
    pieceSVG: WhiteQueen(),
    x: 7,
    y: 3,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-king",
    pieceType: "king",
    pieceColor: "white",
    pieceSVG: WhiteKing(),
    x: 7,
    y: 4,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-bishop-5",
    pieceType: "bishop",
    pieceColor: "white",
    pieceSVG: WhiteBishop(),
    x: 7,
    y: 5,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-knight-6",
    pieceType: "knight",
    pieceColor: "white",
    pieceSVG: WhiteKnight(),
    x: 7,
    y: 6,
    state: "piece",
    selected: false,
    kill: false,
  },
  {
    id: "white-rook-7",
    pieceType: "rook",
    pieceColor: "white",
    pieceSVG: WhiteRook(),
    x: 7,
    y: 7,
    state: "piece",
    selected: false,
    kill: false,
  },
];

const boardArray: SquareOccupancy[][] = [];

for (let x = 0; x < 8; x++) {
  boardArray.push([]);
  for (let y = 0; y < 8; y++) {
    const piece = initialPiecePositions.find(
      (piece) => piece.x === x && piece.y === y
    );
    if (piece) {
      boardArray[x][y] = piece;
    } else {
      boardArray[x][y] = {
        id: `null-${x}-${y}`,
        pieceType: "null",
        pieceSVG: <></>,
        x,
        y,
        state: "empty",
        selected: false,
        kill: false,
      };
    }
  }
}

export { boardArray };
